### PR TITLE
Fix #30

### LINKED ISSUE #30: Bug on julia 0.6
The following script hangs forever:
````julia
using Requires

@require Feather begin
    println("DONE")
end

println("START using")
using Feather
println("END using")
````
But if I modify it like this:
````julia
using Requires

@require Feather begin
    println("DONE")
end

println("START using")
using DataStreams
using FlatBuffers
using Feather
println("END using")
````
everything works. You need the ``Feather`` package to repo this.

I can also get exactly the same problem with the [``IndexedTables``](https://github.com/JuliaComputing/IndexedTables.jl) package, when I replace ``Feather`` in the above repo script with ``IndexedTables``, then everything hangs unless I first load ``PooledArrays``.

### PR DESCRIPTION
**Pull request by vchuravy**
This is my first time taking a look at the Requires internals and
I hope this is the right fix. Is it normal that I get:

```
WARNING: requiring "IndexedTables" in module "Main" did not define a corresponding module.
```

When running the example code from #30?

cc: @davidanthoff

### CODE REVIEW

**Comment by davidanthoff** [comment]
Hm, I don't really understand the internals of Requires, but I have never seen that message, so that might actually be a regression... Not sure, though.

**Comment by vchuravy** [comment]
The warning comes from https://github.com/JuliaLang/julia/blob/d9771af87ca722f87e2298b418fe705239b320b0/src/toplevel.c#L407 which I think corresponds to `Expr(:import, mod)`

**Comment by MikeInnes** [comment]
Can you explain which part of this was bugged, is it just the aliasing of `cond` or something else? Seems like not all the changes are directly related but perhaps I've misunderstood.

**Comment by vchuravy** [comment]
There are two aspects of the fix and I can separate them into different commits. The first thing is the aliasing of the condition variable. After fixing that I got an infinite loop because the modlisteners never got cleaned.

**Comment by MikeInnes** [comment]
Cool, thanks for the explanation. The commits are fine as is but you'll understand that, given the nature of the package, I'd like to avoid any lines that aren't clear to me :)

Does `while isopen(chan); take!(chan)` behave differently from `for val in chan`?

**Comment by vchuravy** [comment]
I don't think so! But I didn't know about `for val in chan` before. I can change that back.

**Comment by vchuravy** [comment]
Is Requires still supporting 0.5?

**Comment by MikeInnes** [comment]
The master branch is 0.6-only. I don't think the bug shows up on 0.5 so this should be fine.

**Comment by MikeInnes** [comment]
Thanks again for the patch 👍

**Comment by vchuravy** [comment]
Yeah Travis is hanging on v0.5 so we should probably disable testing there.

**Comment by MikeInnes** [comment]
Good point, done.

**Pull request merged**
