### PR TITLE
Add `Project.toml` and `test/Project.toml`

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by MikeInnes** [comment]
Would be good to have a manifest as well -- unless Pkg just doesn't generate one, due to the lack of dependencies?

**Comment by DilumAluthge** [comment]
I just tried, and yep, it doesn't generate a Manifest.toml

**Comment by MikeInnes** [comment]
I assume it'd also make sense to delete `REQUIRE` at the same time?

**Comment by DilumAluthge** [comment]
> I assume it'd also make sense to delete `REQUIRE` at the same time?

Done!

**Comment by MikeInnes** [comment]
:+1: Thanks!

**Pull request merged**
